# NumPy

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get dimension
a.ndim

1

In [5]:
#Get shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

GET Type

In [7]:
#Get Type
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('float64')

In [9]:
c = np.array([1,2,3], dtype = 'int16')

In [10]:
c.dtype

dtype('int16')

In [11]:
#Get Size

In [12]:
a.itemsize


4

In [13]:
#Get Total size

In [14]:
a.size

3

In [15]:
a.nbytes

12

### Accessing/Changing specific elements

In [16]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [17]:
#Get a specific element [r,c]
a[1,4]   #Supports negative indexing too

13

In [18]:
#Get a specific row
a[1, :]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
#Get a specific column
a[:,4]

array([ 5, 13])

In [20]:
a[0,1:6:2]

array([2, 4, 6])

In [21]:
a[1,4] = 30
print(a)

a[:,2] = 5
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 30 14 15 16]]
[[ 1  2  5  4  5  6  7  8]
 [ 9 10  5 12 30 14 15 16]]
[[ 1  2  1  4  5  6  7  8]
 [ 9 10  2 12 30 14 15 16]]


#### 3D Example

In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
#Get specific element
b[0,1,1]

4

In [24]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
b[:,1,:] = [[7,8],[3,4]]
print(b)

[[[1 2]
  [7 8]]

 [[5 6]
  [3 4]]]


### Initializing Different types of Arrays

In [26]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
#All 1s matrix
np.ones(5, dtype ='int32')

array([1, 1, 1, 1, 1])

In [29]:
#Any number
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [30]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])

In [31]:
np.full_like(a.shape,4)

array([4, 4])

In [32]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])

In [33]:
#random decimal numbers

np.random.rand(4,2)

array([[0.6743929 , 0.00383631],
       [0.39767436, 0.77692917],
       [0.56576589, 0.2060279 ],
       [0.8009158 , 0.63316594]])

In [34]:
np.random.random_sample(a.shape)

array([[0.04136164, 0.77630362, 0.21792572, 0.55677245, 0.56188903,
        0.314151  , 0.46093104, 0.85052503],
       [0.5184812 , 0.74766171, 0.3700983 , 0.98915354, 0.22304846,
        0.69902888, 0.52563689, 0.78135133]])

In [35]:
a.shape

(2, 8)

In [36]:
#Random integer values
np.random.randint(3,7, size = (3,3))

array([[5, 6, 4],
       [3, 3, 5],
       [6, 5, 3]])

In [37]:
np.identity(4)  #creates identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
#Repeat an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z[:,:]
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [40]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [41]:
b[0] = 100
print(b)

[100   2   3]


In [42]:
print(a)  #a value also gets changed

[100   2   3]


In [43]:
a = np.array([1,2,3])
b = a.copy()       # a value will not change
b[0] = 100
print(a,b)

[1 2 3] [100   2   3]


## Mathematics

In [55]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [45]:
a+2

array([3, 4, 5, 6, 7])

In [46]:
a*2

array([ 2,  4,  6,  8, 10])

In [47]:
a-2

array([-1,  0,  1,  2,  3])

In [48]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [56]:
print(a)
a +=2
print(a)

[1 2 3 4 5]
[3 4 5 6 7]


In [58]:
b = np.array([1,1,1,1,1])
a+b

array([4, 5, 6, 7, 8])

In [59]:
a**2

array([ 9, 16, 25, 36, 49])

In [60]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [61]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [62]:
np.tan(a)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619,  0.87144798])

In [63]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

### Linear Algebra

In [66]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [68]:
a*b   #throws error as both are having different shape

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [69]:
np.matmul(a,b)  #matrix multiplication

array([[6., 6.],
       [6., 6.]])

In [70]:
#Find the determinant

In [71]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
np.linalg.det(c)

1.0

### Statistics

In [81]:
stats = np.array([[1,7,3,4],[5,6,7,8]])
stats

array([[1, 7, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.min(stats)

1

In [79]:
np.max(stats[1])

8

In [82]:
np.max(stats, axis =0)

array([5, 7, 7, 8])

In [83]:
np.max(stats, axis = 1)

array([7, 8])

### Reshaping Arrays

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before.shape

(2, 4)

In [89]:
after = before.reshape(2,2,2)

In [90]:
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### vertically stacking arrays

In [91]:
v1 = [1,2,3,4]
v2 = [5,6,7,8]

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

### Horizontal stack


In [94]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

#### Load file

In [97]:
file_data = np.genfromtxt('data.txt',delimiter =',')
file_data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11.,  1.,  4.,  5.,  6.]])

In [98]:
file_data.astype('int32')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11,  1,  4,  5,  6]])

#### Boolean masking and Advanced indexing

In [99]:
file_data > 5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False,  True]])

In [101]:
file_data[file_data > 5]

array([ 6.,  7.,  8.,  9., 10., 11.,  6.])

##### Indexing with a list in NumPy

In [102]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
a[[1,2,5]]

array([2, 3, 6])

In [103]:
a[3]

4

In [104]:
np.any(file_data > 5, axis = 0)

array([ True,  True,  True,  True,  True])

In [107]:
np.all(file_data > 5, axis = 1)

array([False,  True, False])

In [108]:
((file_data > 3) & (file_data < 10))

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True,  True]])

In [109]:
(~(file_data > 3) & (file_data < 10))

array([[ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [111]:
file_data[0:2, 0:2]

array([[1., 2.],
       [6., 7.]])

In [112]:
file_data[[1,2],[0,1]]

array([6., 1.])

In [113]:
file_data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11.,  1.,  4.,  5.,  6.]])

In [115]:
file_data[[0,2],3:]

array([[4., 5.],
       [5., 6.]])